### ISSUE TITLE
Assessment Feedback

### ISSUE THREAD

**Issue by corneliusellen** [hashmaster3k/mod_0_skills#1]
Hi @hashmaster3k - Solid work on this. I can tell you have a good understanding of Ruby syntax and the relationship between attributes and methods. Can you please implement the feedback below? Let me know if you have any questions:
- the attribute `num_of_cookware` and methods `add_cookware` and `remove_cookware` don't make OO-sense if it lives on an object (`chefs_wok`) that represents a single cookware. Can you come up with a better attribute and method?

**Comment by hashmaster3k** [comment]
Hey @corneliusellen !

Thank you for the feedback! I made the changes as requested. Definitely makes sense now that you mentioned it! I added a boolean variable for if the lid is on/off. I changed the methods to place or remove the lid from the individual cookware.
